### ISSUE TITLE
Plugins.xml missing return_code: 256

### ISSUE THREAD

**Issue by benandern** [Fortressbeast/AConLinux#3]
- task:
      app: "msxml4"
      arch: win32
      name: winetricks
      prefix: $GAMEDIR
      **return_code: 256**

**Comment by Fortressbeast** [comment]
What Linux distro are you running? If you run the Plugins again do you get the same error? Have you tried installing msxml4 manually using WineTricks?

**Comment by benandern** [comment]
I'm running Nobara 37.  I didn't try it manually.  The script kept exiting with 256 at the end of the install and I would have to abort.  I added that line in and, the installer finishes fine.

**Comment by Fortressbeast** [comment]
Interesting. Nobara should work fine since its base is Fedora. I will setup a vm and test the install, not sure why forcing an exit error code would correct any issues though.

**Comment by Fortressbeast** [comment]
I ran the scripts on both Nobara 37 and 38, and I was only able to force it to "hang" if i didnt update and exit decal before trying to install the plugins. Please make sure the follow the directions provided carefully. 

As a side note, not sure which version of Norbara you are using (ie gnome, ect) but I did notice, that the decal icon wasnt showing up unless I cycled the AppIndicator extension. 

I will leave the issue open for a bit longer, but this doesnt seem to be an error with the scripts.

**Comment by benandern** [comment]
I wiped the Wine prefix and files at least 20 times, trying different things because, I was convinced it was me and not the script.  It was this page: [https://www.reddit.com/r/linux_gaming/comments/tb6mtc/lutris_exit_with_return_code_256/](url), that lead me to my result.  And I did exactly as was instructed, in your provided documentation.  Maybe I have something locally that wasn't resolved on each attempt to re-run the script.  The reddit post does mention files that can't be deleted or are possibly still linked somewhere...  Also, I am using you're most recent code.  I did install your original script but, Decal did not work for me at that time.  It was the new script that refused to finish installing...  I'm sure I'm the unicorn here but, Decal is 100% working now.

**Comment by Fortressbeast** [comment]
Ya its probably something local b/c on a fresh OS install, it  worked w/o a hitch. The fact that it appeared to hang points to DenAgent still loaded in memory for some reason. I suppose I can send a sigkill at the start of the Plugins.yaml to make sure that doesnt happen.

Side note:  If you wanted to,  you can clear out lutris complete by removing the prefix, uninstall lutris, then delete ~/.config/lutris and ~/.local/share/lutris. That should put you back to a "fresh start". However, since it is ultimately all working, its probably not worth the effort unless you are having issues with other lutris installs.

Glad to hear it is all working now though.

**Comment by benandern** [comment]
I appreciate your work.  I just want more people to be able to enjoy!  Thanks!

**Comment by Fortressbeast** [comment]
Sure thing. Best of luck in Dereth :)

**Comment by benandern** [comment]
The Pull Request has been updated to include our conclusion and closed.  Thanks again!
